<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://supnum.com/servers"
           xmlns:tns="http://supnum.com/servers"
           elementFormDefault="qualified">

    <!-- type Server -->
    <xs:complexType name="Server">
        <xs:sequence>
            <xs:element name="id" type="xs:long" minOccurs="0"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="ipAddress" type="xs:string"/>
            <xs:element name="running" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <!-- createServer -->
    <xs:element name="createServerRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="ipAddress" type="xs:string"/>
                <xs:element name="running" type="xs:boolean" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="createServerResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="server" type="tns:Server"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- listServers -->
    <xs:element name="listServersRequest" type="xs:anyType"/>

    <xs:element name="listServersResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="servers" type="tns:Server" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- getServerStatus -->
    <xs:element name="getServerStatusRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getServerStatusResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="running" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- startServer -->
    <xs:element name="startServerRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="startServerResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="server" type="tns:Server"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- stopServer -->
    <xs:element name="stopServerRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="stopServerResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="server" type="tns:Server"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- renameServer -->
    <xs:element name="renameServerRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
                <xs:element name="newName" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="renameServerResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="server" type="tns:Server"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- deleteServer -->
    <xs:element name="deleteServerRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="deleteServerResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="success" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
